### Slide 4

In [15]:
dado <- c(1, 2, 3, 4, 5, 6)
dado
is.vector(dado)

[1] 1 2 3 4 5 6

[1] TRUE

### Slide 5

In [24]:
numero <- 5
numero

is.vector(numero)

length(numero)

length(dado)

[1] 5

[1] TRUE

[1] 1

[1] 6

### Slide 6

In [25]:
inteiro <- 1L
texto <- "ace"

typeof(inteiro)
typeof(texto)

[1] "integer"

[1] "character"

### Slide 7

In [26]:
cartas <- 1L:13L
faces <- c("ás", "dois", "três", "quatro",
          "cinco", "seis", "sete", "oito",
          "nove", "dez", "valete", "dama", "rei")

n <- sum(cartas)
is.integer(n)

m <- max(faces)
m

[1] TRUE

[1] "valete"

### Slide 8

In [27]:
dado <- c(1, 2, 3, 4, 5, 6)
dado
typeof(dado)

[1] 1 2 3 4 5 6

[1] "double"

### Slide 9

In [28]:
3 > 4

logico <- c(TRUE, FALSE, 
            3 >= 4, 3 < 4, 
            3 <= 4, 3 < 4, 
            3 != 4, 4 == 4)
logico
typeof(logico)

[1] FALSE

[1]  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

[1] "logical"

### Slide 10

In [17]:
comp <- c(1 + 1i, 1 + 2i, 1 + 3i)
comp

typeof(comp)

[1] 1+1i 1+2i 1+3i

[1] "complex"

### Slide 11

In [18]:
r <- raw(3)
typeof(r)

r[2] <- as.raw(255) 
r[3] <- as.raw(1024) 

r

[1] "raw"

Warning message in eval(expr, envir, enclos):
“out-of-range values treated as 0 in coercion to raw”

[1] 00 ff 00

### Slide 12

In [20]:
dado <- c(1,2,3,4,5,6)
attributes(dado)

names(dado) <- c("um", "dois", "três", 
                 'quatro', 'cinco', 'seis')
attributes(dado)

NULL

$names
[1] "um"     "dois"   "três"   "quatro" "cinco"  "seis"

### Slide 13

In [21]:
names(dado) <- NULL
dado

[1] 1 2 3 4 5 6

### Slide 14

In [29]:
dado <- 1:6
dim(dado) <- c(2, 3)
dado

attributes(dado)

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

$dim
[1] 2 3

### Slide 15

In [23]:
m <- matrix(dado, nrow = 2)
m

n <- matrix(dado, nrow = 2, byrow = TRUE)
n

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6

### Slide 16

In [30]:
typeof(dado)

class(dado)

attributes(dado)

[1] "integer"

[1] "matrix" "array"

$dim
[1] 2 3

### Slide 17

In [31]:
now <- Sys.time()
now

typeof(now)

class(now)

[1] "2022-09-30 13:02:07 -03"

[1] "double"

[1] "POSIXct" "POSIXt"

### Slide 18

In [32]:
genero <- factor(c("feminino", "masculino", 
                   "feminino", "masculino"))

typeof(genero)

attributes(genero)

[1] "integer"

$levels
[1] "feminino"  "masculino"

$class
[1] "factor"

### Slide 19

In [35]:
unclass(genero)

n <- unclass(genero)

as.integer(genero)

as.character(genero)

[1] 1 2 1 2
attr(,"levels")
[1] "feminino"  "masculino"

[1] 1 2 1 2

[1] "feminino"  "masculino" "feminino"  "masculino"

### Slide 21

In [36]:
sum(c(TRUE, TRUE, FALSE, FALSE))
sum(c(1, 1, 0, 0))
as.character(1)
as.logical(1)
as.numeric(FALSE)

[1] 2

[1] 2

[1] "1"

[1] TRUE

[1] 0

### Slide 22

In [37]:
df <- data.frame(
    face = c("ás", "dois", "quatro"),  
    naipe = c("ouros", "copas", "paus"), 
    valor = c(1, 2, 4))
df

  face   naipe valor
1 ás     ouros 1
2 dois   copas 2
3 quatro paus  4

### Slide 23

In [39]:
write.csv(df, file = "cartas.csv", 
          row.names = FALSE, quote=FALSE)

cartas <- read.csv("cartas.csv")