In [1]:
faces <- c("ás", "dois", "três", "quatro",
           "cinco", "seis", "sete", "oito",
           "nove", "dez", "valete", "dama", "rei")
naipes = c("ouros", "copas", "paus", "espadas")
baralho <- expand.grid(face=faces, naipe=naipes)
baralho

   face   naipe
1  ás     ouros
2  dois   ouros
3  três   ouros
4  quatro ouros
5  cinco  ouros
6  seis   ouros
7  sete   ouros
8  oito   ouros
9  nove   ouros
10 dez    ouros
11 valete ouros
12 dama   ouros
13 rei    ouros
14 ás     copas
15 dois   copas
16 três   copas
17 quatro copas
18 cinco  copas
19 seis   copas
20 sete   copas
21 oito   copas
22 nove   copas
23 dez    copas
24 valete copas
25 dama   copas
26 rei    copas
27 ás     paus
28 dois   paus
29 três   paus
30 quatro paus
31 cinco  paus
32 seis   paus
33 sete   paus
34 oito   paus
35 nove   paus
36 dez    paus
37 valete paus
38 dama   paus
39 rei    paus
40 ás     espadas
41 dois   espadas
42 três   espadas
43 quatro espadas
44 cinco  espadas
45 seis   espadas
46 sete   espadas
47 oito   espadas
48 nove   espadas
49 dez    espadas
50 valete espadas
51 dama   espadas
52 rei    espadas

In [2]:
baralho$valor <- c(1:13, 1:13, 1:13, 1:13)
baralho
head(baralho)

   face   naipe   valor
1  ás     ouros    1
2  dois   ouros    2
3  três   ouros    3
4  quatro ouros    4
5  cinco  ouros    5
6  seis   ouros    6
7  sete   ouros    7
8  oito   ouros    8
9  nove   ouros    9
10 dez    ouros   10
11 valete ouros   11
12 dama   ouros   12
13 rei    ouros   13
14 ás     copas    1
15 dois   copas    2
16 três   copas    3
17 quatro copas    4
18 cinco  copas    5
19 seis   copas    6
20 sete   copas    7
21 oito   copas    8
22 nove   copas    9
23 dez    copas   10
24 valete copas   11
25 dama   copas   12
26 rei    copas   13
27 ás     paus     1
28 dois   paus     2
29 três   paus     3
30 quatro paus     4
31 cinco  paus     5
32 seis   paus     6
33 sete   paus     7
34 oito   paus     8
35 nove   paus     9
36 dez    paus    10
37 valete paus    11
38 dama   paus    12
39 rei    paus    13
40 ás     espadas  1
41 dois   espadas  2
42 três   espadas  3
43 quatro espadas  4
44 cinco  espadas  5
45 seis   espadas  6
46 sete   espadas  7
47 oito   espadas  8
48 nove   espadas  9
49 dez    espadas 10
50 valete espadas 11
51 dama   espadas 12
52 rei    espadas 13

  face   naipe valor
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 3
4 quatro ouros 4
5 cinco  ouros 5
6 seis   ouros 6

In [3]:
baralho[1, 1] 
baralho[1, "face"] 
baralho[c(1,2), 1] 
baralho[ , 1]

[1] ás
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

[1] ás
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

[1] ás   dois
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

 [1] ás     dois   três   quatro cinco  seis   sete   oito   nove   dez
[11] valete dama   rei    ás     dois   três   quatro cinco  seis   sete
[21] oito   nove   dez    valete dama   rei    ás     dois   três   quatro
[31] cinco  seis   sete   oito   nove   dez    valete dama   rei    ás
[41] dois   três   quatro cinco  seis   sete   oito   nove   dez    valete
[51] dama   rei
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

In [4]:
baralho[c(11,14), "face"] 
baralho[c(11,14), 1] 
baralho$face[c(11,14)]

[1] valete ás
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

[1] valete ás
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

[1] valete ás
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

In [5]:
baralho[11, 1:2] 
baralho[c(11,14), 1:2] 
baralho[c(11,14), c("face", "naipe")]

   face   naipe
11 valete ouros

   face   naipe
11 valete ouros
14 ás     copas

   face   naipe
11 valete ouros
14 ás     copas

In [6]:
baralho[c(11,14), "face", drop=FALSE] 
baralho[c(11,14), 1, drop=FALSE]

   face
11 valete
14 ás

   face
11 valete
14 ás

In [7]:
baralho[c(1:13), 1] 
baralho[-c(14:52), 1] 
baralho[1:3, -1]

 [1] ás     dois   três   quatro cinco  seis   sete   oito   nove   dez
[11] valete dama   rei
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

 [1] ás     dois   três   quatro cinco  seis   sete   oito   nove   dez
[11] valete dama   rei
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

  naipe valor
1 ouros 1
2 ouros 2
3 ouros 3

In [8]:
baralho[ , ]
baralho[1, ] 
baralho[ , 1]

   face   naipe   valor
1  ás     ouros    1
2  dois   ouros    2
3  três   ouros    3
4  quatro ouros    4
5  cinco  ouros    5
6  seis   ouros    6
7  sete   ouros    7
8  oito   ouros    8
9  nove   ouros    9
10 dez    ouros   10
11 valete ouros   11
12 dama   ouros   12
13 rei    ouros   13
14 ás     copas    1
15 dois   copas    2
16 três   copas    3
17 quatro copas    4
18 cinco  copas    5
19 seis   copas    6
20 sete   copas    7
21 oito   copas    8
22 nove   copas    9
23 dez    copas   10
24 valete copas   11
25 dama   copas   12
26 rei    copas   13
27 ás     paus     1
28 dois   paus     2
29 três   paus     3
30 quatro paus     4
31 cinco  paus     5
32 seis   paus     6
33 sete   paus     7
34 oito   paus     8
35 nove   paus     9
36 dez    paus    10
37 valete paus    11
38 dama   paus    12
39 rei    paus    13
40 ás     espadas  1
41 dois   espadas  2
42 três   espadas  3
43 quatro espadas  4
44 cinco  espadas  5
45 seis   espadas  6
46 sete   espadas  7
47 oito   espadas  8
48 nove   espadas  9
49 dez    espadas 10
50 valete espadas 11
51 dama   espadas 12
52 rei    espadas 13

  face naipe valor
1 ás   ouros 1

 [1] ás     dois   três   quatro cinco  seis   sete   oito   nove   dez
[11] valete dama   rei    ás     dois   três   quatro cinco  seis   sete
[21] oito   nove   dez    valete dama   rei    ás     dois   três   quatro
[31] cinco  seis   sete   oito   nove   dez    valete dama   rei    ás
[41] dois   três   quatro cinco  seis   sete   oito   nove   dez    valete
[51] dama   rei
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

In [9]:
baralho[1, c(TRUE, TRUE, FALSE)]

  face naipe
1 ás   ouros

In [10]:
filtro <- baralho$valor < 3
baralho[filtro, ]
baralho[baralho$valor < 3,]

   face naipe   valor
1  ás   ouros   1
2  dois ouros   2
14 ás   copas   1
15 dois copas   2
27 ás   paus    1
28 dois paus    2
40 ás   espadas 1
41 dois espadas 2

   face naipe   valor
1  ás   ouros   1
2  dois ouros   2
14 ás   copas   1
15 dois copas   2
27 ás   paus    1
28 dois paus    2
40 ás   espadas 1
41 dois espadas 2

In [11]:
ordem <- sample(1:nrow(baralho))
ordem
cartas <- baralho[ordem,]
cartas

 [1] 37 45 47 29 50 26 30 20 42  3  5 27  2 43 39 12 33 32 14 21 13 25 44 23 10
[26]  6 17  8 40 19  4 36  7 22 52 16  9 11 18 24 35 49 34 31  1 41 15 46 28 38
[51] 51 48

   face   naipe   valor
37 valete paus    11
45 seis   espadas  6
47 oito   espadas  8
29 três   paus     3
50 valete espadas 11
26 rei    copas   13
30 quatro paus     4
20 sete   copas    7
42 três   espadas  3
3  três   ouros    3
5  cinco  ouros    5
27 ás     paus     1
2  dois   ouros    2
43 quatro espadas  4
39 rei    paus    13
12 dama   ouros   12
33 sete   paus     7
32 seis   paus     6
14 ás     copas    1
21 oito   copas    8
13 rei    ouros   13
25 dama   copas   12
44 cinco  espadas  5
23 dez    copas   10
10 dez    ouros   10
6  seis   ouros    6
17 quatro copas    4
8  oito   ouros    8
40 ás     espadas  1
19 seis   copas    6
4  quatro ouros    4
36 dez    paus    10
7  sete   ouros    7
22 nove   copas    9
52 rei    espadas 13
16 três   copas    3
9  nove   ouros    9
11 valete ouros   11
18 cinco  copas    5
24 valete copas   11
35 nove   paus     9
49 dez    espadas 10
34 oito   paus     8
31 cinco  paus     5
1  ás     ouros    1
41 dois   espadas  2
15 dois   copas    2
46 sete   espadas  7
28 dois   paus     2
38 dama   paus    12
51 dama   espadas 12
48 nove   espadas  9

In [12]:
embaralhar <- function(baralho) {
  ordem <- sample(1:nrow(baralho))
  return(baralho[ordem,])
}
cartas <- embaralhar(baralho)
cartas

   face   naipe   valor
8  oito   ouros    8
35 nove   paus     9
42 três   espadas  3
22 nove   copas    9
17 quatro copas    4
40 ás     espadas  1
11 valete ouros   11
12 dama   ouros   12
24 valete copas   11
37 valete paus    11
52 rei    espadas 13
31 cinco  paus     5
51 dama   espadas 12
48 nove   espadas  9
21 oito   copas    8
18 cinco  copas    5
33 sete   paus     7
7  sete   ouros    7
26 rei    copas   13
38 dama   paus    12
4  quatro ouros    4
39 rei    paus    13
30 quatro paus     4
46 sete   espadas  7
49 dez    espadas 10
9  nove   ouros    9
1  ás     ouros    1
41 dois   espadas  2
16 três   copas    3
27 ás     paus     1
28 dois   paus     2
32 seis   paus     6
15 dois   copas    2
29 três   paus     3
34 oito   paus     8
13 rei    ouros   13
45 seis   espadas  6
44 cinco  espadas  5
50 valete espadas 11
43 quatro espadas  4
3  três   ouros    3
19 seis   copas    6
14 ás     copas    1
20 sete   copas    7
36 dez    paus    10
5  cinco  ouros    5
47 oito   espadas  8
23 dez    copas   10
6  seis   ouros    6
2  dois   ouros    2
25 dama   copas   12
10 dez    ouros   10