### Slide 3

In [16]:
u <- "https://github.com/eogasawara/R/raw/main/baralho.rda"
load(url(u))
head(baralho)

  face   naipe valor
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 3
4 quatro ouros 4
5 cinco  ouros 5
6 seis   ouros 6

### Slide 4

In [19]:
save(baralho, file="baralho.rda")
rm(baralho)

   face   naipe
1  ás     ouros
2  dois   ouros
3  três   ouros
4  quatro ouros
5  cinco  ouros
6  seis   ouros
7  sete   ouros
8  oito   ouros
9  nove   ouros
10 dez    ouros
11 valete ouros
12 dama   ouros
13 rei    ouros
14 ás     copas
15 dois   copas
16 três   copas
17 quatro copas
18 cinco  copas
19 seis   copas
20 sete   copas
21 oito   copas
22 nove   copas
23 dez    copas
24 valete copas
25 dama   copas
26 rei    copas
27 ás     paus
28 dois   paus
29 três   paus
30 quatro paus
31 cinco  paus
32 seis   paus
33 sete   paus
34 oito   paus
35 nove   paus
36 dez    paus
37 valete paus
38 dama   paus
39 rei    paus
40 ás     espadas
41 dois   espadas
42 três   espadas
43 quatro espadas
44 cinco  espadas
45 seis   espadas
46 sete   espadas
47 oito   espadas
48 nove   espadas
49 dez    espadas
50 valete espadas
51 dama   espadas
52 rei    espadas

### Slide 5

In [20]:
load(file="baralho.rda")
head(baralho)

  face   naipe
1 ás     ouros
2 dois   ouros
3 três   ouros
4 quatro ouros
5 cinco  ouros
6 seis   ouros

### Slide 6

In [10]:
baralho$idx <- 1:52
head(baralho)

  face   naipe valor idx
1 ás     ouros 1     1
2 dois   ouros 2     2
3 três   ouros 3     3
4 quatro ouros 4     4
5 cinco  ouros 5     5
6 seis   ouros 6     6

### Slide 7

In [11]:
baralho$idx[c(1,3,5)] <- 1
head(baralho)
baralho$idx[4:6] <- baralho$idx[4:6] + 1
head(baralho)

  face   naipe valor idx
1 ás     ouros 1     1
2 dois   ouros 2     2
3 três   ouros 3     1
4 quatro ouros 4     4
5 cinco  ouros 5     1
6 seis   ouros 6     6

  face   naipe valor idx
1 ás     ouros 1     1
2 dois   ouros 2     2
3 três   ouros 3     1
4 quatro ouros 4     5
5 cinco  ouros 5     2
6 seis   ouros 6     7

### Slide 8

In [12]:
baralho$idx <- 1:52
vec <- (baralho$idx %% 2 == 1)
idx <- baralho$idx[vec]
idx
cartas <- baralho[vec,]
cartas

 [1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51

   face   naipe  valor idx
1  ás     ouros   1     1
3  três   ouros   3     3
5  cinco  ouros   5     5
7  sete   ouros   7     7
9  nove   ouros   9     9
11 valete ouros  11    11
13 rei    ouros  13    13
15 dois   copas   2    15
17 quatro copas   4    17
19 seis   copas   6    19
21 oito   copas   8    21
23 dez    copas  10    23
25 dama   copas  12    25
27 ás     paus    1    27
29 três   paus    3    29
31 cinco  paus    5    31
33 sete   paus    7    33
35 nove   paus    9    35
37 valete paus   11    37
39 rei    paus   13    39
41 dois   espada  2    41
43 quatro espada  4    43
45 seis   espada  6    45
47 oito   espada  8    47
49 dez    espada 10    49
51 dama   espada 12    51

### Slide 9

In [14]:
1 > 2
1 > c(0, 1, 2)
c(1, 2, 3) == c(3, 2, 1)
1 %in% c(3, 4, 5)
c(1, 2, 3) %in% c(3, 4, 5)

[1] FALSE

[1]  TRUE FALSE FALSE

[1] FALSE  TRUE FALSE

[1] FALSE

[1] FALSE FALSE  TRUE

### Slide 10

In [18]:
baralho[ , ]
baralho[1, ] 
baralho[ , 1]

   face   naipe  valor
1  ás     ouros   1
2  dois   ouros   2
3  três   ouros   3
4  quatro ouros   4
5  cinco  ouros   5
6  seis   ouros   6
7  sete   ouros   7
8  oito   ouros   8
9  nove   ouros   9
10 dez    ouros  10
11 valete ouros  11
12 dama   ouros  12
13 rei    ouros  13
14 ás     copas   1
15 dois   copas   2
16 três   copas   3
17 quatro copas   4
18 cinco  copas   5
19 seis   copas   6
20 sete   copas   7
21 oito   copas   8
22 nove   copas   9
23 dez    copas  10
24 valete copas  11
25 dama   copas  12
26 rei    copas  13
27 ás     paus    1
28 dois   paus    2
29 três   paus    3
30 quatro paus    4
31 cinco  paus    5
32 seis   paus    6
33 sete   paus    7
34 oito   paus    8
35 nove   paus    9
36 dez    paus   10
37 valete paus   11
38 dama   paus   12
39 rei    paus   13
40 ás     espada  1
41 dois   espada  2
42 três   espada  3
43 quatro espada  4
44 cinco  espada  5
45 seis   espada  6
46 sete   espada  7
47 oito   espada  8
48 nove   espada  9
49 dez    espada 10
50 valete espada 11
51 dama   espada 12
52 rei    espada 13

  face naipe valor
1 ás   ouros 1

 [1] ás     dois   três   quatro cinco  seis   sete   oito   nove   dez
[11] valete dama   rei    ás     dois   três   quatro cinco  seis   sete
[21] oito   nove   dez    valete dama   rei    ás     dois   três   quatro
[31] cinco  seis   sete   oito   nove   dez    valete dama   rei    ás
[41] dois   três   quatro cinco  seis   sete   oito   nove   dez    valete
[51] dama   rei
13 Levels: ás dois três quatro cinco seis sete oito nove dez valete ... rei

### Slide 12

In [19]:
baralho[1, c(TRUE, TRUE, FALSE)]

  face naipe
1 ás   ouros

### Slide 13

In [20]:
filtro <- baralho$valor < 3
baralho[filtro, ]
baralho[baralho$valor < 3,]

   face naipe  valor
1  ás   ouros  1
2  dois ouros  2
14 ás   copas  1
15 dois copas  2
27 ás   paus   1
28 dois paus   2
40 ás   espada 1
41 dois espada 2

   face naipe  valor
1  ás   ouros  1
2  dois ouros  2
14 ás   copas  1
15 dois copas  2
27 ás   paus   1
28 dois paus   2
40 ás   espada 1
41 dois espada 2

### Slide 14

In [24]:
ordem <- sample(1:nrow(baralho))
ordem
cartas <- baralho[ordem,]
cartas

 [1] 29 35 31  7 46 12 27 26 51  1 32 23 43 48 52 45 44 21  6  4 39 10 34 37 14
[26] 50 11 24 33  3 17 38 42 18 16 30 49 25 22 47  8 40 28 13 41  9 36  5 15  2
[51] 20 19

   face   naipe  valor
29 três   paus    3
35 nove   paus    9
31 cinco  paus    5
7  sete   ouros   7
46 sete   espada  7
12 dama   ouros  12
27 ás     paus    1
26 rei    copas  13
51 dama   espada 12
1  ás     ouros   1
32 seis   paus    6
23 dez    copas  10
43 quatro espada  4
48 nove   espada  9
52 rei    espada 13
45 seis   espada  6
44 cinco  espada  5
21 oito   copas   8
6  seis   ouros   6
4  quatro ouros   4
39 rei    paus   13
10 dez    ouros  10
34 oito   paus    8
37 valete paus   11
14 ás     copas   1
50 valete espada 11
11 valete ouros  11
24 valete copas  11
33 sete   paus    7
3  três   ouros   3
17 quatro copas   4
38 dama   paus   12
42 três   espada  3
18 cinco  copas   5
16 três   copas   3
30 quatro paus    4
49 dez    espada 10
25 dama   copas  12
22 nove   copas   9
47 oito   espada  8
8  oito   ouros   8
40 ás     espada  1
28 dois   paus    2
13 rei    ouros  13
41 dois   espada  2
9  nove   ouros   9
36 dez    paus   10
5  cinco  ouros   5
15 dois   copas   2
2  dois   ouros   2
20 sete   copas   7
19 seis   copas   6

### Slide 15

In [25]:
embaralhar <- function(baralho) {
  ordem <- sample(1:nrow(baralho))
  return(baralho[ordem,])
}
cartas <- embaralhar(baralho)
cartas

   face   naipe  valor
20 sete   copas   7
3  três   ouros   3
47 oito   espada  8
33 sete   paus    7
43 quatro espada  4
1  ás     ouros   1
34 oito   paus    8
39 rei    paus   13
23 dez    copas  10
32 seis   paus    6
6  seis   ouros   6
17 quatro copas   4
18 cinco  copas   5
31 cinco  paus    5
42 três   espada  3
40 ás     espada  1
7  sete   ouros   7
51 dama   espada 12
14 ás     copas   1
16 três   copas   3
4  quatro ouros   4
8  oito   ouros   8
11 valete ouros  11
28 dois   paus    2
44 cinco  espada  5
5  cinco  ouros   5
48 nove   espada  9
52 rei    espada 13
10 dez    ouros  10
21 oito   copas   8
30 quatro paus    4
49 dez    espada 10
50 valete espada 11
15 dois   copas   2
35 nove   paus    9
24 valete copas  11
45 seis   espada  6
46 sete   espada  7
2  dois   ouros   2
13 rei    ouros  13
27 ás     paus    1
38 dama   paus   12
37 valete paus   11
41 dois   espada  2
36 dez    paus   10
22 nove   copas   9
29 três   paus    3
19 seis   copas   6
25 dama   copas  12
12 dama   ouros  12
26 rei    copas  13
9  nove   ouros   9