In [12]:
#slide 3
u <- "https://github.com/eogasawara/R/raw/main/baralho.rda"
load(url(u))
head(baralho)

  face   naipe
1 ás     ouros
2 dois   ouros
3 três   ouros
4 quatro ouros
5 cinco  ouros
6 seis   ouros

In [13]:
#slide 4
save(baralho, file="baralho.rda")
rm(baralho)

In [14]:
#slide 5
load(file="baralho.rda")
head(baralho)

  face   naipe
1 ás     ouros
2 dois   ouros
3 três   ouros
4 quatro ouros
5 cinco  ouros
6 seis   ouros

In [15]:
#slide 6
baralho$idx <- 1:52
head(baralho)

  face   naipe idx
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 3
4 quatro ouros 4
5 cinco  ouros 5
6 seis   ouros 6

In [16]:
#slide 7
baralho$idx[c(1,3,5)] <- 1
head(baralho)
baralho$idx[4:6] <- baralho$idx[4:6] + 1
head(baralho)

  face   naipe idx
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 1
4 quatro ouros 4
5 cinco  ouros 1
6 seis   ouros 6

  face   naipe idx
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 1
4 quatro ouros 5
5 cinco  ouros 2
6 seis   ouros 7

In [17]:
#slide 8
baralho$idx <- 1:52
vec <- (baralho$idx %% 2 == 1)
idx <- baralho$idx[vec]
idx
cartas <- baralho[vec,]
cartas

 [1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51

   face   naipe   idx
1  ás     ouros    1
3  três   ouros    3
5  cinco  ouros    5
7  sete   ouros    7
9  nove   ouros    9
11 valete ouros   11
13 rei    ouros   13
15 dois   copas   15
17 quatro copas   17
19 seis   copas   19
21 oito   copas   21
23 dez    copas   23
25 dama   copas   25
27 ás     paus    27
29 três   paus    29
31 cinco  paus    31
33 sete   paus    33
35 nove   paus    35
37 valete paus    37
39 rei    paus    39
41 dois   espadas 41
43 quatro espadas 43
45 seis   espadas 45
47 oito   espadas 47
49 dez    espadas 49
51 dama   espadas 51

In [18]:
#slide 9
1 > 2
1 > c(0, 1, 2)
c(1, 2, 3) == c(3, 2, 1)
1 %in% c(3, 4, 5)
c(1, 2, 3) %in% c(3, 4, 5)

[1] FALSE

[1]  TRUE FALSE FALSE

[1] FALSE  TRUE FALSE

[1] FALSE

[1] FALSE FALSE  TRUE

In [19]:
#slide 10
x <- baralho$face == "dama" & baralho$naipe == "espadas"
head(baralho[x,])

x <- baralho$face == "dama" | baralho$naipe == "espadas"
head(baralho[x,])

   face naipe   idx
51 dama espadas 51

   face naipe   idx
12 dama ouros   12
25 dama copas   25
38 dama paus    38
40 ás   espadas 40
41 dois espadas 41
42 três espadas 42

In [20]:
#slide 11
1 + NA
NA == 1
c(NA, 1:50)
mean(c(NA, 1:50))
mean(c(NA, 1:50), na.rm = TRUE)

[1] NA

[1] NA

 [1] NA  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
[26] 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
[51] 50

[1] NA

[1] 25.5

In [21]:
#slide 13
filtro <- baralho$valor < 3
baralho[filtro, ]
baralho[baralho$valor < 3,]

     face naipe idx

     face naipe idx

In [22]:
#slide 14
ordem <- sample(1:nrow(baralho))
ordem
cartas <- baralho[ordem,]
cartas

 [1]  3 39 16 49  4 43 45 15  6 42 22 14 38 41 29 23 40 52  1 13 28 11  8 50 24
[26] 44 26 17 25 51 48 36  5  2 12 35  9 19 21 33 18 47 31 10 37 46  7 34 32 27
[51] 20 30

   face   naipe   idx
3  três   ouros    3
39 rei    paus    39
16 três   copas   16
49 dez    espadas 49
4  quatro ouros    4
43 quatro espadas 43
45 seis   espadas 45
15 dois   copas   15
6  seis   ouros    6
42 três   espadas 42
22 nove   copas   22
14 ás     copas   14
38 dama   paus    38
41 dois   espadas 41
29 três   paus    29
23 dez    copas   23
40 ás     espadas 40
52 rei    espadas 52
1  ás     ouros    1
13 rei    ouros   13
28 dois   paus    28
11 valete ouros   11
8  oito   ouros    8
50 valete espadas 50
24 valete copas   24
44 cinco  espadas 44
26 rei    copas   26
17 quatro copas   17
25 dama   copas   25
51 dama   espadas 51
48 nove   espadas 48
36 dez    paus    36
5  cinco  ouros    5
2  dois   ouros    2
12 dama   ouros   12
35 nove   paus    35
9  nove   ouros    9
19 seis   copas   19
21 oito   copas   21
33 sete   paus    33
18 cinco  copas   18
47 oito   espadas 47
31 cinco  paus    31
10 dez    ouros   10
37 valete paus    37
46 sete   espadas 46
7  sete   ouros    7
34 oito   paus    34
32 seis   paus    32
27 ás     paus    27
20 sete   copas   20
30 quatro paus    30

In [23]:
#slide 15
embaralhar <- function(baralho) {
  ordem <- sample(1:nrow(baralho))
  return(baralho[ordem,])
}
cartas <- embaralhar(baralho)
cartas

   face   naipe   idx
7  sete   ouros    7
9  nove   ouros    9
32 seis   paus    32
25 dama   copas   25
37 valete paus    37
45 seis   espadas 45
6  seis   ouros    6
3  três   ouros    3
51 dama   espadas 51
14 ás     copas   14
12 dama   ouros   12
21 oito   copas   21
48 nove   espadas 48
18 cinco  copas   18
23 dez    copas   23
34 oito   paus    34
39 rei    paus    39
10 dez    ouros   10
44 cinco  espadas 44
5  cinco  ouros    5
30 quatro paus    30
38 dama   paus    38
15 dois   copas   15
28 dois   paus    28
4  quatro ouros    4
46 sete   espadas 46
43 quatro espadas 43
33 sete   paus    33
16 três   copas   16
13 rei    ouros   13
29 três   paus    29
1  ás     ouros    1
17 quatro copas   17
20 sete   copas   20
47 oito   espadas 47
42 três   espadas 42
24 valete copas   24
27 ás     paus    27
26 rei    copas   26
41 dois   espadas 41
31 cinco  paus    31
36 dez    paus    36
22 nove   copas   22
8  oito   ouros    8
11 valete ouros   11
19 seis   copas   19
2  dois   ouros    2
52 rei    espadas 52
35 nove   paus    35
50 valete espadas 50
40 ás     espadas 40
49 dez    espadas 49