In [24]:
u <- "https://github.com/eogasawara/R/raw/main/baralho.rda"
load(url(u))
head(baralho)

  face   naipe
1 ás     ouros
2 dois   ouros
3 três   ouros
4 quatro ouros
5 cinco  ouros
6 seis   ouros

In [25]:
save(baralho, file="baralho.rda")
rm(baralho)

In [26]:
load(file="baralho.rda")
head(baralho)

  face   naipe
1 ás     ouros
2 dois   ouros
3 três   ouros
4 quatro ouros
5 cinco  ouros
6 seis   ouros

In [27]:
baralho$idx <- 1:52
head(baralho)

  face   naipe idx
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 3
4 quatro ouros 4
5 cinco  ouros 5
6 seis   ouros 6

In [28]:
baralho$idx[c(1,3,5)] <- 1
head(baralho)
baralho$idx[4:6] <- baralho$idx[4:6] + 1
head(baralho)

  face   naipe idx
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 1
4 quatro ouros 4
5 cinco  ouros 1
6 seis   ouros 6

  face   naipe idx
1 ás     ouros 1
2 dois   ouros 2
3 três   ouros 1
4 quatro ouros 5
5 cinco  ouros 2
6 seis   ouros 7

In [29]:
baralho$idx <- 1:52
vec <- (baralho$idx %% 2 == 1)
idx <- baralho$idx[vec]
idx
cartas <- baralho[vec,]
cartas

 [1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51

   face   naipe   idx
1  ás     ouros    1
3  três   ouros    3
5  cinco  ouros    5
7  sete   ouros    7
9  nove   ouros    9
11 valete ouros   11
13 rei    ouros   13
15 dois   copas   15
17 quatro copas   17
19 seis   copas   19
21 oito   copas   21
23 dez    copas   23
25 dama   copas   25
27 ás     paus    27
29 três   paus    29
31 cinco  paus    31
33 sete   paus    33
35 nove   paus    35
37 valete paus    37
39 rei    paus    39
41 dois   espadas 41
43 quatro espadas 43
45 seis   espadas 45
47 oito   espadas 47
49 dez    espadas 49
51 dama   espadas 51

In [30]:
1 > 2
1 > c(0, 1, 2)
c(1, 2, 3) == c(3, 2, 1)
1 %in% c(3, 4, 5)
c(1, 2, 3) %in% c(3, 4, 5)

[1] FALSE

[1]  TRUE FALSE FALSE

[1] FALSE  TRUE FALSE

[1] FALSE

[1] FALSE FALSE  TRUE

In [31]:
x <- baralho$face == "dama" & baralho$naipe == "espadas"
head(baralho[x,])

x <- baralho$face == "dama" | baralho$naipe == "espadas"
head(baralho[x,])

   face naipe   idx
51 dama espadas 51

   face naipe   idx
12 dama ouros   12
25 dama copas   25
38 dama paus    38
40 ás   espadas 40
41 dois espadas 41
42 três espadas 42

In [32]:
1 + NA
NA == 1
c(NA, 1:50)
mean(c(NA, 1:50))
mean(c(NA, 1:50), na.rm = TRUE)

[1] NA

[1] NA

 [1] NA  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
[26] 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
[51] 50

[1] NA

[1] 25.5

In [33]:
filtro <- baralho$valor < 3
baralho[filtro, ]
baralho[baralho$valor < 3,]

     face naipe idx

     face naipe idx

In [34]:
ordem <- sample(1:nrow(baralho))
ordem
cartas <- baralho[ordem,]
cartas

 [1]  4 37 26 46 28 38 10 15  9 47 51 17  1 48 41 22 30 32 39 16 11  8 34 18 36
[26]  3 45 52 44  7  5 35 20 31 49 14 25 23 13 21 42 24 50 12 33 27 29  2  6 40
[51] 43 19

   face   naipe   idx
4  quatro ouros    4
37 valete paus    37
26 rei    copas   26
46 sete   espadas 46
28 dois   paus    28
38 dama   paus    38
10 dez    ouros   10
15 dois   copas   15
9  nove   ouros    9
47 oito   espadas 47
51 dama   espadas 51
17 quatro copas   17
1  ás     ouros    1
48 nove   espadas 48
41 dois   espadas 41
22 nove   copas   22
30 quatro paus    30
32 seis   paus    32
39 rei    paus    39
16 três   copas   16
11 valete ouros   11
8  oito   ouros    8
34 oito   paus    34
18 cinco  copas   18
36 dez    paus    36
3  três   ouros    3
45 seis   espadas 45
52 rei    espadas 52
44 cinco  espadas 44
7  sete   ouros    7
5  cinco  ouros    5
35 nove   paus    35
20 sete   copas   20
31 cinco  paus    31
49 dez    espadas 49
14 ás     copas   14
25 dama   copas   25
23 dez    copas   23
13 rei    ouros   13
21 oito   copas   21
42 três   espadas 42
24 valete copas   24
50 valete espadas 50
12 dama   ouros   12
33 sete   paus    33
27 ás     paus    27
29 três   paus    29
2  dois   ouros    2
6  seis   ouros    6
40 ás     espadas 40
43 quatro espadas 43
19 seis   copas   19

In [35]:
embaralhar <- function(baralho) {
  ordem <- sample(1:nrow(baralho))
  return(baralho[ordem,])
}
cartas <- embaralhar(baralho)
cartas

   face   naipe   idx
29 três   paus    29
35 nove   paus    35
47 oito   espadas 47
16 três   copas   16
45 seis   espadas 45
21 oito   copas   21
26 rei    copas   26
31 cinco  paus    31
40 ás     espadas 40
14 ás     copas   14
39 rei    paus    39
24 valete copas   24
19 seis   copas   19
27 ás     paus    27
17 quatro copas   17
9  nove   ouros    9
8  oito   ouros    8
5  cinco  ouros    5
49 dez    espadas 49
3  três   ouros    3
30 quatro paus    30
37 valete paus    37
48 nove   espadas 48
28 dois   paus    28
10 dez    ouros   10
46 sete   espadas 46
7  sete   ouros    7
6  seis   ouros    6
42 três   espadas 42
44 cinco  espadas 44
2  dois   ouros    2
36 dez    paus    36
50 valete espadas 50
11 valete ouros   11
38 dama   paus    38
4  quatro ouros    4
34 oito   paus    34
12 dama   ouros   12
1  ás     ouros    1
33 sete   paus    33
25 dama   copas   25
43 quatro espadas 43
51 dama   espadas 51
13 rei    ouros   13
20 sete   copas   20
22 nove   copas   22
18 cinco  copas   18
41 dois   espadas 41
52 rei    espadas 52
15 dois   copas   15
23 dez    copas   23
32 seis   paus    32